### PR TITLE
Refactor/ods input

### PR DESCRIPTION
**Pull request by aesteves60**

### CODE REVIEW

File: packages/ods/src/components/input/tests/navigation/ods-input.e2e2.ts [hunk 1]
```diff
@@ -0,0 +1,208 @@
+import type { E2EElement, E2EPage } from '@stencil/core/testing';
```
Comment (dpellier) [inline packages/ods/src/components/input/tests/navigation/ods-input.e2e2.ts:1]: file name is wrong `e2e2` => `e2e`

File: packages/ods/src/components/input/tests/navigation/ods-input.e2e2.ts [hunk 2]
```diff
@@ -0,0 +1,208 @@
...
+
+      await page.keyboard.press('Tab');
+      await page.keyboard.press('Tab');
+      await page.keyboard.press('Space');
+      await page.waitForChanges();
+
+      expect(await el.getProperty('value')).toBe('value');
+      await page.keyboard.press('Enter');
+      await page.waitForChanges();
+      await button.click();
```
Comment (dpellier) [inline packages/ods/src/components/input/tests/navigation/ods-input.e2e2.ts:116]: miss en expect between Enter and click

File: packages/ods/src/components/input/tests/navigation/ods-input.e2e2.ts [hunk 3]
```diff
@@ -0,0 +1,208 @@
...
+    });
+
+    it('should toggle masked when Space on button', async() => {
+      await setup('<ods-input is-masked value="value"></ods-input>');
+      const odsToggleMaskSpy = await page.spyOnEvent('odsToggleMask');
+      expect(await input.getProperty('type')).toBe('password');
+
+      await page.keyboard.press('Tab');
+      await page.keyboard.press('Tab');
+      await page.keyboard.press(' ');
```
Comment (dpellier) [inline packages/ods/src/components/input/tests/navigation/ods-input.e2e2.ts:157]: either use ` ` or `Space` to be consistent with other tests

File: packages/ods/src/components/input/tests/navigation/ods-input.e2e2.ts [hunk 4]
```diff
@@ -0,0 +1,208 @@
...
+      await page.keyboard.press('Tab');
+      await page.keyboard.press('Tab');
+      await page.keyboard.press('Space');
+      await page.waitForChanges();
+
+      expect(await input.getProperty('type')).toBe('password');
+
+      await page.keyboard.press('Enter');
+      await page.waitForChanges();
+      await button.click();
```
Comment (dpellier) [inline packages/ods/src/components/input/tests/navigation/ods-input.e2e2.ts:190]: same expect here

File: packages/ods/src/components/input/package.json [hunk 5]
```diff
@@ -0,0 +1,19 @@
...
+  "version": "17.1.0",
+  "private": true,
+  "description": "ODS Input component",
+  "main": "dist/index.cjs.js",
+  "collection": "dist/collection/collection-manifest.json",
+  "scripts": {
+    "clean": "rimraf .stencil coverage dist docs-api www",
+    "doc": "typedoc --pretty --plugin ../../../scripts/typedoc-plugin-decorator.js && node ../../../scripts/generate-typedoc-md.js",
+    "lint:scss": "stylelint 'src/components/**/*.scss'",
+    "lint:ts": "eslint 'src/**/*.{js,ts,tsx}'",
```
Comment (dpellier) [inline packages/ods/src/components/input/package.json:12]: update with latest cmd (check other components)

File: packages/ods/src/components/input/tests/rendering/ods-input.e2e.ts [hunk 6]
```diff
@@ -0,0 +1,166 @@
...
+
+  describe('part', () => {
+    it('should render with custom style applied', async() => {
+      await setup('<ods-input></ods-input>', 'ods-input::part(input) { width: 100px }');
+      const partStyle = await part.getComputedStyle();
+      expect(partStyle.getPropertyValue('width')).toBe('100px');
+    });
+  });
+
+  describe('method:clear', () => {
```
Comment (dpellier) [inline packages/ods/src/components/input/tests/rendering/ods-input.e2e.ts:39]: not sure this is the right place for those
`rendering` should contains the tests about things that change the actual render (ex: setting is-loading does display a spinner, is-masked add a button, ...)
we can add specific directories like `methods` and `events` that will contains dedicated tests

File: packages/ods/src/components/input/tests/rendering/ods-input.spec.ts [hunk 7]
```diff
@@ -0,0 +1,376 @@
...
+
+    describe('type', () => {
+      it('should be reflected', async() => {
+        const typeValue = ODS_INPUT_TYPE.number;
+        await setup(`<ods-input type="${typeValue}"></ods-input>`);
+
+        expect(root?.getAttribute('type')).toBe(typeValue);
+      });
+
+      it('should not be set by default', async() => {
```
Comment (dpellier) [inline packages/ods/src/components/input/tests/rendering/ods-input.spec.ts:354]: rename

File: packages/ods/src/style/_input.scss [hunk 8]
```diff
@@ -0,0 +1,18 @@
...
+@mixin ods-input() {
+  box-sizing: border-box;
+  border: theme.$ods-border-width-sm solid theme.$ods-form-element-border-color-default;
+  border-radius: theme.$ods-border-radius-sm;
+  cursor: text;
+  padding: 4px 8px;
+  width: 100%;
+  height: 32px;
+  line-height: 16px;
+  font-size: 16px;
```
Comment (dpellier) [inline packages/ods/src/style/_input.scss:13]: `1rem`

File: packages/ods/src/style/_input.scss [hunk 9]
```diff
@@ -0,0 +1,18 @@
...
+
+@mixin ods-input() {
+  box-sizing: border-box;
+  border: theme.$ods-border-width-sm solid theme.$ods-form-element-border-color-default;
+  border-radius: theme.$ods-border-radius-sm;
+  cursor: text;
+  padding: 4px 8px;
+  width: 100%;
+  height: 32px;
+  line-height: 16px;
```
Comment (dpellier) [inline packages/ods/src/style/_input.scss:12]: `1rem`

File: packages/ods/vue/tests/_app/src/components/ods-input.vue [hunk 10]
```diff
@@ -0,0 +1,23 @@
+<template>
+  <ods-input name="ods-input" @ods-value-change="() => console.log('test')"></ods-input>
```
Comment (dpellier) [inline packages/ods/vue/tests/_app/src/components/ods-input.vue:2]: use `onOdsValueChange`?

File: packages/ods/vue/tests/e2e/ods-input.e2e.ts [hunk 11]
```diff
@@ -0,0 +1,23 @@
...
+  });
+
+  it('render the component correctly', async () => {
+    const elem = await page.$('ods-input');
+    const boundingBox = await elem?.boundingBox();
+
+    expect(boundingBox?.height).toBeGreaterThan(0);
+    expect(boundingBox?.width).toBeGreaterThan(0);
+  });
+});
```
Comment (dpellier) [inline packages/ods/vue/tests/e2e/ods-input.e2e.ts:23]: test value change?

File: packages/storybook/stories/components/input/migration_.from.17.x.mdx [hunk 12]
```diff
@@ -0,0 +1,219 @@
+import { Meta } from '@storybook/blocks';
+import * as SkeletonStories from './input.stories';
+
+<Meta of={SkeletonStories} name='Migration From 17.x' />
```
Comment (dpellier) [inline packages/storybook/stories/components/input/migration_.from.17.x.mdx:4]: `InputStories`

File: packages/storybook/stories/components/input/migration_.from.17.x.mdx [hunk 13]
```diff
@@ -0,0 +1,219 @@
...
+
+# Skeleton - migrate from v17 to v18
```
Comment (dpellier) [inline packages/storybook/stories/components/input/migration_.from.17.x.mdx:6]: `Input`

File: packages/storybook/stories/components/input/migration_.from.17.x.mdx [hunk 14]
```diff
@@ -0,0 +1,219 @@
...
+
+Has been updated.
+
+You can use the new `isRequired` attribute to obtain the same behavior.
+
+`forbidden-values` <img src="https://img.shields.io/badge/removed-FF0000" />
+
+Has been removed.
+
+You can replace it a regax on the `pattern` attributes.
```
Comment (dpellier) [inline packages/storybook/stories/components/input/migration_.from.17.x.mdx:57]: "You can replace it with a regex on the `pattern` attribute."

File: packages/storybook/stories/components/input/migration_.from.17.x.mdx [hunk 15]
```diff
@@ -0,0 +1,219 @@
...
+Has been removed.
+
+Input is now `inline-block` by default.
+You can add some style directly on the component if you want to override that.
+
+`label` <img src="https://img.shields.io/badge/removed-FF0000" />
+
+Has been removed.
+
+For add a label on the input wrapped it with the component `form-field`.
```
Comment (dpellier) [inline packages/storybook/stories/components/input/migration_.from.17.x.mdx:70]: `To add a label ...`

File: packages/storybook/stories/components/input/migration_.from.17.x.mdx [hunk 16]
```diff
@@ -0,0 +1,219 @@
...
+
+`prefix-value` <img src="https://img.shields.io/badge/removed-FF0000" />
+
+Have been removed.
+
+No need anymore. Can't be migrate.
```
Comment (dpellier) [inline packages/storybook/stories/components/input/migration_.from.17.x.mdx:76]: `This feature is not supported anymore`

**Review by dpellier — CHANGES_REQUESTED** [review]

File: packages/ods/src/components/input/src/components/ods-input/ods-input.tsx [hunk 17]
```diff
@@ -0,0 +1,183 @@
...
+  @Prop({ reflect: true }) public max?: number;
+  @Prop({ reflect: true }) public maxlength?: number;
+  @Prop({ reflect: true }) public min?: number;
+  @Prop({ reflect: true }) public minlength?: number;
+  @Prop({ reflect: true }) public name!: string;
+  @Prop({ reflect: true }) public pattern?: string;
+  @Prop({ reflect: true }) public placeholder?: string;
+  @Prop({ reflect: true }) public step?: number;
+  @Prop({ reflect: true }) public type: OdsInputType = ODS_INPUT_TYPE.text;
+  @Prop({ mutable: true, reflect: true }) public value?: string | number = undefined;
```
[the remark this answers is not in the document]
Comment (aesteves60) [reply packages/ods/src/components/input/src/components/ods-input/ods-input.tsx:42]: Don't think the value should be need

File: packages/ods/src/components/input/src/components/ods-input/ods-input.tsx [hunk 18]
```diff
@@ -0,0 +1,183 @@
...
+  @Event() odsValueChange!: EventEmitter<OdsInputEventValueChange>;
+
+  @Method()
+  async clear(): Promise<void> {
+    if (this.isDisabled) {
+      return;
+    }
+    this.value = undefined;
+    this.odsClear.emit();
+    return;
```
[the remark this answers is not in the document]
Comment (aesteves60) [reply packages/ods/src/components/input/src/components/ods-input/ods-input.tsx:57]: It's for return void and not a `Promise<CustomEvent<void>>` if I return `this.odsClear.emit()`

File: packages/ods/src/components/input/src/components/ods-input/ods-input.tsx (hunk 17 above)
[the remark this answers is not in the document]
Comment (dpellier) [reply packages/ods/src/components/input/src/components/ods-input/ods-input.tsx:42]: my bad I saw an initialization but of wrong type so `?` fixes it

File: packages/ods/src/components/input/src/components/ods-input/ods-input.tsx (hunk 18 above)
[the remark this answers is not in the document]
Comment (dpellier) [reply packages/ods/src/components/input/src/components/ods-input/ods-input.tsx:57]: just don't return anything?
```
async clear(): Promise<void> {
    if (this.isDisabled) {
      return;
    }
    this.value = undefined;
    this.odsClear.emit();
  }
```

File: packages/ods/src/components/input/src/components/ods-input/ods-input.tsx [hunk 19]
```diff
@@ -0,0 +1,183 @@
...
+  @AttachInternals() private internals!: ElementInternals;
+
+  @State() isPassword = false;
+  @State() internalError = false;
+
+  @Prop({ reflect: true }) public ariaLabel: HTMLElement['ariaLabel'] = null;
+  @Prop({ reflect: true }) public ariaLabelledby?: string;
+  @Prop({ reflect: true }) public defaultValue?: string | number;
+  @Prop({ reflect: true }) public hasError: boolean = false;
+  @Prop({ reflect: true }) public isClearable?: boolean;
```
[the remark this answers is not in the document]
Comment (aesteves60) [reply packages/ods/src/components/input/src/components/ods-input/ods-input.tsx:27]: ok but not masked

File: packages/ods/src/components/input/src/components/ods-input/ods-input.tsx [hunk 20]
```diff
@@ -0,0 +1,183 @@
...
+  @Prop({ reflect: true }) public placeholder?: string;
+  @Prop({ reflect: true }) public step?: number;
+  @Prop({ reflect: true }) public type: OdsInputType = ODS_INPUT_TYPE.text;
+  @Prop({ mutable: true, reflect: true }) public value?: string | number = undefined;
+
+  @Event() odsBlur!: EventEmitter<void>;
+  @Event() odsClear!: EventEmitter<void>;
+  @Event() odsToggleMask!: EventEmitter<void>;
+  @Event() odsReset!: EventEmitter<void>;
+  @Event() odsValueChange!: EventEmitter<OdsInputEventValueChange>;
```
[the remark this answers is not in the document]
Comment (aesteves60) [reply packages/ods/src/components/input/src/components/ods-input/ods-input.tsx:48]: If you want, but I don't think it will fix the problem caused by the integrator's misunderstanding.

File: packages/ods/src/components/input/src/components/ods-input/ods-input.tsx [hunk 21]
```diff
@@ -24,12 +24,12 @@ export class OdsInput {
...
-  @Prop({ reflect: true }) public isClearable?: boolean;
+  @Prop({ reflect: true }) public isClearable?: boolean = false;
   @Prop({ reflect: true }) public isDisabled: boolean = false;
-  @Prop({ reflect: true }) public isLoading?: boolean;
+  @Prop({ reflect: true }) public isLoading?: boolean = false;
   @Prop({ mutable: true, reflect: true }) public isMasked?: boolean;
-  @Prop({ reflect: true }) public isReadonly?: boolean;
-  @Prop({ reflect: true }) public isRequired?: boolean;
+  @Prop({ reflect: true }) public isReadonly?: boolean = false;
+  @Prop({ reflect: true }) public isRequired?: boolean = false;
```
Comment (dpellier) [inline packages/ods/src/components/input/src/components/ods-input/ods-input.tsx:32]: you can remove the `?` then if the prop has a default value

File: packages/ods/src/components/input/tests/behaviour/ods-input.e2e.ts [hunk 22]
```diff
@@ -0,0 +1,114 @@
+import type { E2EElement, E2EPage } from '@stencil/core/testing';
+import { newE2EPage } from '@stencil/core/testing';
+
+describe('ods-input accessibility', () => {
```
Comment (dpellier) [inline packages/ods/src/components/input/tests/behaviour/ods-input.e2e.ts:4]: rename

File: packages/ods/src/components/input/tests/rendering/ods-input.spec.ts [hunk 23]
```diff
@@ -351,8 +351,8 @@ describe('ods-input rendering', () => {
         expect(root?.getAttribute('type')).toBe(typeValue);
       });
 
-      it('should not be set by default', async() => {
-        await setup(`<ods-input></ods-input>`);
+      it('should not be set by default with type "text"', async() => {
```
Comment (dpellier) [inline packages/ods/src/components/input/tests/rendering/ods-input.spec.ts:354]: should be set by default with ...

**Review by dpellier — CHANGES_REQUESTED** [review]

**Review by dpellier — CHANGES_REQUESTED** [review]
I see already a few issue with the actions:
- clearable should appear only after more than 1 character si typed
- clearable color should be gray
- focus is square on the actions (clearable, masked), did you use the mixin?
- cursor on actions should be the same as an ods-button
- actions icon is not correctly centered vertically

**Review by astagnol — CHANGES_REQUESTED** [review]
Eye icon should not be displayed by default when we arrive on Demo page
Capture d’écran 2024-04-18 à 09 11 42

Types in the field on Demo -> should not be in error state.

On Demo, set 'isMasked' to false and 'type' to number:
Capture d’écran 2024-04-18 à 09 14 23

Click on the field -> move your mouse outside -> border color is now blue (it should not change)

**isClearable**
- When isClearable is true, icon should be displayed after user types one character.
- clearable icon is a secondary icon, it should be in neutral-600

We should have a cursor pointer when you hover clearable and eye icons.

When the user types in the field, text color should be ods-color-text.

**Disabled**
Style should not change on hover.

**Accessibility**
- focus on icon is not correct (UI). It should be same as:
Capture d’écran 2024-04-18 à 09 58 23
- cannot focus on isClearable icon when eye icon is displayed

File: packages/ods/src/components/input/src/index.ts [hunk 24]
```diff
@@ -0,0 +1,3 @@
+export { OdsInput } from './components/ods-input/ods-input';
+export { ODS_INPUT_TYPE, ODS_INPUT_TYPES, type OdsInputType } from './constants/input-type';
+export { type OdsInputEventValueChange } from './interfaces/events';
```
Comment (dpellier) [inline packages/ods/src/components/input/src/index.ts:3]: expose detail also

**Review by dpellier — CHANGES_REQUESTED** [review]

File: packages/ods/src/components/input/src/components/ods-input/ods-input.tsx [hunk 25]
```diff
@@ -0,0 +1,183 @@
...
+  @Prop({ reflect: true }) public min?: number;
+  @Prop({ reflect: true }) public minlength?: number;
+  @Prop({ reflect: true }) public name!: string;
+  @Prop({ reflect: true }) public pattern?: string;
+  @Prop({ reflect: true }) public placeholder?: string;
+  @Prop({ reflect: true }) public step?: number;
+  @Prop({ reflect: true }) public type: OdsInputType = ODS_INPUT_TYPE.text;
+  @Prop({ mutable: true, reflect: true }) public value?: string | number = undefined;
+
+  @Event() odsBlur!: EventEmitter<void>;
```
Comment (dpellier) [inline packages/ods/src/components/input/src/components/ods-input/ods-input.tsx:44]: We should also trigger an `odsFocus` event

**Review by dpellier — CHANGES_REQUESTED** [review]

File: packages/ods/src/components/input/src/controller/ods-input.ts [hunk 26]
```diff
@@ -0,0 +1,20 @@
+async function handleKeySpace(event: KeyboardEvent, isDisabled: boolean, callback: () => Promise<void>): Promise<void> {
+  event.preventDefault();
+  if(event.key === ' ' && !isDisabled) {
+    await callback();
+  }
+}
+
+function setFormValue(internals: ElementInternals, value?: number | string): void {
+  internals?.setFormValue?.(value?.toString() ?? '');
```
Comment (dpellier) [inline packages/ods/src/components/input/src/controller/ods-input.ts:9]: remove unnecessary `?`
`internals.setFormValue(value?.toString() ?? '');`

**Review by dpellier — CHANGES_REQUESTED** [review]

**Review by dpellier — CHANGES_REQUESTED** [review]
Got this warning when trying to reset an input without default value set
Capture d’écran 2024-04-19 à 11 54 14

**Review by astagnol — CHANGES_REQUESTED** [review]
Types in the field on Demo -> should not be in error (it is working well on documentation page)

**isClearable**
Focus should be back to the field when it has been cleared (on both mouse click & keyboard nav)

**Disabled & readonly**
I updated the figma so you can now use the following variables (you'll need to re-generate the tokens):
$ods-form-element-foreground-color-disabled
$ods-form-element-foreground-color-readonly

**Accessibility**
Focus on icon is still not correct (but the icon is not aligned vertically by the way, same goes for loading icon)
Capture d’écran 2024-04-19 à 14 26 56

Why display false or true at the top the field for this control?
Capture d’écran 2024-04-19 à 14 45 44

File: packages/ods/src/components/input/src/components/ods-input/ods-input.scss [hunk 27]
```diff
@@ -0,0 +1,100 @@
...
+      &:focus {
+        border-color: theme.$ods-form-element-border-color-focused;
+      }
+
+      &:hover {
+        border-color: theme.$ods-form-element-border-color-hover;
+      }
+    }
+
+    &--disabled {
```
Comment (dpellier) [inline packages/ods/src/components/input/src/components/ods-input/ods-input.scss:70]: can be moved into the mixin using native pseudo-selector `&:disabled` and then remove the class from the template
(when possible it's better to use native pseudo, this way people get it when using the mixin without depending on BEM class name)

File: packages/ods/src/components/input/src/components/ods-input/ods-input.scss [hunk 28]
```diff
@@ -0,0 +1,100 @@
...
+      background-color: theme.$ods-color-neutral-100;
+      cursor: not-allowed;
+      user-select: none;
```
Comment (dpellier) [inline packages/ods/src/components/input/src/components/ods-input/ods-input.scss:73]: not sure needed

File: packages/ods/src/components/input/src/components/ods-input/ods-input.tsx [hunk 29]
```diff
@@ -0,0 +1,183 @@
...
+    this.odsReset.emit();
+    return;
+  }
+
+  @Watch('isMasked')
+  onMaskedChange(): void {
+    this.isPassword = isPassword(this.isMasked);
+  }
+
+  @Watch('error')
```
Comment (dpellier) [inline packages/ods/src/components/input/src/components/ods-input/ods-input.tsx:90]: should be removed, there is no more any prop `error`

File: packages/ods/src/components/input/src/components/ods-input/ods-input.tsx [hunk 30]
```diff
@@ -0,0 +1,183 @@
...
+  onErrorChange(): void {
+    this.internalError = !this.inputEl?.validity?.valid ?? this.hasError;
```
Comment (dpellier) [inline packages/ods/src/components/input/src/components/ods-input/ods-input.tsx:92]: is `internalError` state still usefull?

**Review by dpellier — CHANGES_REQUESTED** [review]

File: packages/ods/src/components/input/tests/rendering/ods-input.spec.ts [hunk 31]
```diff
@@ -0,0 +1,376 @@
...
+    page = await newSpecPage({
+      components: [OdsInput],
+      html,
+    });
+
+    root = page.root;
+    rootInstance = page.rootInstance;
+  }
+
+  describe('methods', () => {
```
Comment (dpellier) [inline packages/ods/src/components/input/tests/rendering/ods-input.spec.ts:21]: move to behaviour spec file too

**Review by dpellier — CHANGES_REQUESTED** [review]

File: packages/ods/src/components/input/tests/behaviour/ods-input.spec.ts [hunk 32]
```diff
@@ -0,0 +1,79 @@
+jest.mock('../../src/controller/ods-input');
+import type { SpecPage } from '@stencil/core/testing';
+import { newSpecPage } from '@stencil/core/testing';
+import { OdsInput } from '../../src';
+
+describe('ods-input rendering', () => {
```
Comment (dpellier) [inline packages/ods/src/components/input/tests/behaviour/ods-input.spec.ts:6]: rename

**Review by dpellier — CHANGES_REQUESTED** [review]
please check remaining unresolved previous reviews

File: packages/ods/src/components/input/src/components/ods-input/ods-input.scss [hunk 33]
```diff
@@ -31,6 +32,10 @@ $ods-input-input-padding-right: calc($ods-input-actions-button-width + $ods-inpu
       cursor: pointer;
     }
 
+    &__icon {
+      font-size: 16px;
```
Comment (dpellier) [inline packages/ods/src/components/input/src/components/ods-input/ods-input.scss:36]: 1rem

File: packages/ods/src/components/input/src/components/ods-input/ods-input.scss [hunk 34]
```diff
@@ -94,6 +101,7 @@ $ods-input-input-padding-right: calc($ods-input-actions-button-width + $ods-inpu
     &:disabled {
       ~ .ods-input__actions {
         cursor: not-allowed;
+        pointer-events: none;
```
Comment (dpellier) [inline packages/ods/src/components/input/src/components/ods-input/ods-input.scss:104]: would be best to manage this on the button style instead
update the `:active` selector with a `:not(:disabled)`

**Review by dpellier — CHANGES_REQUESTED** [review]
readonly state still has active action buttons

**Review by feoche — CHANGES_REQUESTED** [review]
Global : 
- [ ] Not working in Safari 16.1 (this.attachInternals is not a function)

Docs : 
- [x] Missing links below Component overview
- [x] Missing readonly + placeholder examples
- [x] Using "My button" text in Migration doc instead of input

Demo : 
- [ ] A11y issues (to be discussed) : 
image

Style : 
- [ ] Text is overflowed on loading state
image
- [ ] Icon inside action button is not vertically aligned, fixed by setting a font-size on the button itself
image
- [x] Spinner should be 8px away from right border (in loading state) instead of 4px
- [ ] Icons in action buttons are not centered in Chromium
image
- [x] Loading icon has a cursor: pointer on it
- [ ] Input of type `number` show arrow icons in Chromium when hover/focus
- [ ] Is `pattern` attribute working ?

**Comment by aesteves60** [comment]
>     * [ ]  Is `pattern` attribute working ?

Yes but we don't update the error anymore. The error is return in the `odsChange` event

**Review by dpellier — CHANGES_REQUESTED** [review]
issue with input type `number` and `isClearable` true:
- type a number, like `11`
=> clearable is visible
- type a letter `11e`
=> clearable disappear

I guess the value is reset when not matching a number, but input should stay clearable in that case

**Review by feoche — CHANGES_REQUESTED** [review]
- [ ] Not vertically aligned in Chromium, can be fixed using `display: inherit` + `justify-content: center` + `align-items: center`
image

**Review by dpellier — APPROVED** [review]

**Review by Leotheluck — APPROVED** [review]

**Review by feoche — APPROVED** [review]
